# Project: ontap
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ontap.o
LINKOBJ  = ontap.o
LIBS     = -L"C:/Users/nbvh/Dev-Cpp/MinGW64/lib" -L"C:/Users/nbvh/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/nbvh/Dev-Cpp/MinGW64/include" -I"C:/Users/nbvh/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/nbvh/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/nbvh/Dev-Cpp/MinGW64/include" -I"C:/Users/nbvh/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/nbvh/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/nbvh/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ontap.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

ontap.o: ontap.c
	$(CC) -c ontap.c -o ontap.o $(CFLAGS)
